---
abstract: 'Show a 500 error page if you die'
author:
  - 'Justin Hunter <justin.d.hunter@gmail.com>'
build_requires:
  FindBin: 0
  Plack::Builder: 0
  Plack::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-DiePretty
no_index:
  directory:
    - t
    - inc
requires:
  FindBin: 0
  Path::Class: 0
  Plack::Middleware: 0
  Template: 0
  Try::Tiny: 0
  perl: 5.008001
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Plack-Middleware-DiePretty
  license: http://dev.perl.org/licenses/
  repository: https://github.com/arcanez/Plack-Middleware-DiePretty
version: 0.001
